# Generated by Django 2.1.5 on 2019-05-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_auto_20190520_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(error_messages={'invalid': 'Category name already exists.'}, max_length=128, unique=True),
        ),
    ]
