# Generated by Django 2.1.5 on 2019-05-23 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0008_auto_20190523_0527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='first_visit',
        ),
        migrations.RemoveField(
            model_name='page',
            name='last_visit',
        ),
    ]
